# Generated by Django 3.1.3 on 2020-11-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
